[versions]
appcompat = "1.7.1"
composeBom = "2025.08.01"
constraintlayout = "2.2.1"
datastorePreferences = "1.1.7"
gradle = "8.13.0"
junit = "4.13.2"
material = "1.13.0"
runner = "1.7.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
compose = "1.9.0"
material3 = "1.3.2"
sortDependencies = "0.15"
versions = "0.52.0"
foundation = "1.9.0"
runtimeLivedata = "1.9.0"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref="foundation" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref="material3" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sortDependencies = { id = "com.squareup.sort-dependencies", version.ref = "sortDependencies" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }