[versions]
appcompat = "1.7.1"
constraintlayout = "2.2.1"
gradle = "8.12.0"
junit = "4.13.2"
runner = "1.7.0"
kotlin = "2.2.0"
coreKtx = "1.16.0"

[libraries]
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }